- src/apps/ui/App.vue
- src/public/index.html
Added new hello world div and styling
> Added new hello world div and styling

- src/apps/ui/App.vue
- src/public/index.html
Input button and commit button
> Input button and commit button

- src/apps/ui/App.vue
- src/public/index.html
Modify isdone value on button press
> Completion Conditionals

- src/apps/ui/App.vue
date posted and modified added
> date posted and modified added

- src/apps/ui/components/regular/RegularHeader.vue
- src/apps/ui/pages/regular/About.vue
- src/apps/ui/pages/regular/Features.vue
- src/apps/ui/pages/regular/Login.vue
- src/apps/ui/router.vue.js
added about and login and killed faq and features
> added features and links to header navbar

- src/apps/ui/components/regular/RegularFooter.vue
since we are not moving forward with the footer nav bar the language item has been discarded
copyright added
github and discord links added
> footer nav bar refactor

- src/apps/ui/pages/dashboard/tools/calculators/OneRepMaxCalculator.vue.vue
> 1rm calculation with button

- package-lock.json
- package.json
- src/apps/ui/components/dashboard/DashboardFooter.vue
- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/pages/dashboard/Profile.vue
- src/apps/ui/pages/dashboard/Settings.vue
- src/apps/ui/pages/dashboard/tools/Tools.vue
- scaffold settings page
- change menu link title from h2 to h4
- momnet.js
> Mass changes

- src/apps/ui/pages/dashboard/DashboardContact.vue
- src/apps/ui/pages/dashboard/Settings.vue
- src/apps/ui/router.vue.js
feat: added a back button on dashboard contact page
> feat: added a back button on dashboard contact page

- src/apps/ui/pages/dashboard/DashboardContact.vue
- src/apps/ui/pages/dashboard/Profile.vue
- src/apps/ui/pages/dashboard/Sessions.vue
- src/apps/ui/pages/dashboard/Settings.vue
- src/apps/ui/pages/dashboard/Videos.vue
- src/apps/ui/pages/dashboard/tools/Tools.vue
refactor: changed container padding x to use more space
> refactor: changed container padding x to use more space

- src/apps/api/auth/auth.controller.js
- src/apps/api/auth/auth.queries.js
- src/apps/api/auth/auth.router.js
- src/apps/api/auth/auth.validation.js
- src/apps/api/v1/users/users.queries.js
- src/database/migrations/20220604090530_schema.js
- src/services/email.service.js
- update user_details schema not to have verification token null
- auth queries verifyUser
> Email account verifying process

- src/config/knexfile.js
bug: Fixed an issue causing the database not to switch over URL vs individual credentials.
> 'bug: Fixed an issue causing the database not to switch over URL vs individual credentials.

- .vscode/settings.json
- package-lock.json
- package.json
- src/apps/api/auth/auth.controller.js
- src/apps/ui/components/shared/Login.vue
- src/apps/ui/main.vue.js
- src/apps/ui/pages/dashboard/Profile.vue
- src/apps/ui/router.vue.js
- src/apps/ui/store/user.store.js
- full function authentication workflow
- pina state persistence via plugging (we no longer have to manage ourselves via localstorage)
- refactor most of the login API call on Login/Signn .vue.
> feat: added a fully function authentication workflow via api/ui

- src/services/email.service.js
chad bot error message was not allowing any pther users to open app in dev environ
> chad error message

- src/apps/ui/pages/dashboard/settings/account/UserDetails.vue
bug: fixed an issue where updating user details was sending empty fields
> bug: fixed an issue where updating user details was sending empty fields

- src/apps/ui/pages/dashboard/sessions/Categories.vue
- src/config/env.js
feat: the ability to add exe cate via ui
> feat: the ability to add exe cate via ui

- src/apps/api/v1/exercise-categories/exercise-categories.queries.js
- src/apps/api/v1/exercises/exercises.controller.js
- src/apps/api/v1/exercises/exercises.router.js
- src/apps/api/v1/exercises/exercises.validation.js
- src/apps/app.controller.js
- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/pages/dashboard/tools/Tools.vue
feat: the ability to choose exercise from session details
> feat: the ability to choose exercise from session details

- src/apps/api/v1/exercise-categories/exercise-categories.controller.js
- src/apps/api/v1/exercise-categories/exercise-categories.queries.js
- src/apps/api/v1/exercise-categories/exercise-categories.router.js
- src/apps/ui/pages/dashboard/sessions/Categories.vue
- src/apps/ui/pages/dashboard/sessions/Exercises.vue
bug: fixed an issue causing exercises categories to not return when on none empty database entries
> bug: fixed an issue causing exercises categories to not return when on none empty database entries

- .vscode/settings.json
- src/apps/api/v1/sessions/sessions.queries.js
- src/apps/api/v1/sets/sets.router.js
- src/apps/ui/components/dashboard/SessionDetails.vue
- src/database/migrations/20220718015611_sessions.js
- src/database/seeds/02_local-admin-data.seed.js
feat: exercises will now populated underneath session details card
> feat: exercises will now populated underneath session details card

- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/pages/dashboard/sessions/Blocks.vue
- src/database/seeds/02_local-admin-data.seed.js
- Added block duration label and seed exercises note data
> feat: added block duration label and seed exercises note data

- src/apps/ui/pages/dashboard/sessions/Blocks.vue
> bug: fixed days was not included when week is more than 1

- src/apps/api/v1/sessions/sessions.controller.js
- src/apps/api/v1/sessions/sessions.queries.js
- src/apps/api/v1/sessions/sessions.validation.js
- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/pages/dashboard/sessions/Sessions.vue
- src/database/migrations/20220718015611_sessions.js
feat: tack unfinished session and reflect on sessions list page
> feat: tack unfinished session and reflect on sessions list page

- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/components/dashboard/headers/SessionsHeader.vue
- src/apps/ui/pages/dashboard/sessions/Blocks.vue
feat: added a reminder to add data
> feat: added a reminder to add data

- src/apps/ui/pages/regular/Features.vue
> featurette descriptions

- src/apps/ui/components/dashboard/SessionDetails.vue
feat: added clear buttons beside models footer
> feat: added clear buttons beside models footer

- src/apps/api/v1/sessions/sessions.queries.js
- src/apps/api/v1/sets/sets.controller.js
- src/apps/api/v1/sets/sets.queries.js
- src/apps/api/v1/sets/sets.router.js
- src/apps/api/v1/sets/sets.validation.js
- src/apps/ui/components/dashboard/SessionDetails.vue
feat: now we can remove sets and update sets from within
> feat: now we can remove sets and update sets from within

- src/apps/ui/components/dashboard/SessionDetails.vue
- feat: added toggle button for set notes
> feat: added toggle button for set notes

- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/components/dashboard/headers/SessionsHeader.vue
- src/apps/ui/pages/dashboard/sessions/Blocks.vue
- src/apps/ui/pages/dashboard/sessions/Categories.vue
- src/apps/ui/pages/dashboard/sessions/Exercises.vue
feat: fixed vue was creating new el everytime dom changes
> feat: fixed vue was creating new el everytime dom changes

- src/apps/ui/components/dashboard/SessionDetails.vue
feat: reset sets reactive data after adding a new set
> feat: reset sets reactive data after adding a new set

- package-lock.json
- package.json
- src/apps/api/v1/sessions/sessions.controller.js
- src/apps/api/v1/sessions/sessions.queries.js
- src/apps/api/v1/sessions/sessions.router.js
- src/apps/api/v1/sessions/sessions.validation.js
- src/apps/ui/pages/dashboard/sessions/Sessions.vue
- src/database/db.js
- feat: added a load more button for the session page
> Load more button for sessions page

- src/apps/ui/pages/dashboard/sessions/Sessions.vue
feat: fixed show more button showing up on all pages
> Fix load more showing up on all pages

- src/apps/api/v1/sessions/sessions.queries.js
- src/apps/ui/components/dashboard/SessionDetails.vue
bug: possible fix for sessoin is was not inserting when creating a session at times
> bug: possible fix for session id is null

- src/apps/api/v1/exercises/exercises.controller.js
- src/apps/api/v1/exercises/exercises.queries.js
- src/apps/api/v1/exercises/exercises.router.js
- src/apps/api/v1/exercises/exercises.validation.js
- src/apps/api/v1/logs/logs.controller.js
- src/apps/api/v1/logs/logs.queries.js
- src/apps/api/v1/logs/logs.router.js
- src/apps/api/v1/logs/logs.validation.js
- src/apps/api/v1/sessions/sessions.queries.js
- src/apps/api/v1/sessions/sessions.router.js
- src/apps/api/v1/sets/sets.router.js
- src/apps/api/v1/sets/sets.validation.js
- src/apps/api/v1/v1.js
- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/pages/dashboard/sessions/Sessions.vue
- src/config/rateLimiter.js
- src/database/migrations/20220718015637_logs.js
- src/database/migrations/20220718015638_sets.js
- src/database/migrations/20220728035410_activities.js
- extract variables from the sessions table into the variables table
- instead of logging JSON and the actual table, we are now just joining into a different table.
- added variables table to track individual variables, this is going to be much easy when we start pulling report for sleep, bodyweight
> feat: refactor systems into smaller component

- src/apps/api/v1/sessions/sessions.queries.js
- src/apps/ui/components/dashboard/SessionDetails.vue
bug: fixed exercise was not adding
> bug: fixed exercise was not adding

- src/apps/api/v1/users/users.router.js
- src/apps/api/v1/v1.js
- src/apps/api/v1/variables/variables.controller.js
- src/apps/api/v1/variables/variables.queries.js
- src/apps/api/v1/variables/variables.router.js
- src/apps/api/v1/variables/variables.validation.js
- src/apps/ui/pages/dashboard/Profile.vue
- feat: added a reactive body weight report for the profile page
> feat: added a reactive body weight report for profile page

- package-lock.json
- package.json
- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/main.vue.js
- src/apps/ui/pages/dashboard/sessions/Blocks.vue
- src/apps/ui/pages/dashboard/sessions/Categories.vue
- src/apps/ui/pages/dashboard/sessions/Exercises.vue
feat: added v-auto-animate and more animation into most lists
> feat: added v-auto-animate and more animation into most lists

- src/apps/api/v1/logs/logs.controller.js
- src/apps/api/v1/sessions/sessions.queries.js
refactor: use full join instead of inner joined so we don't have to call DB twice
> refactor: use full join instead of inner joined so we don't have to call DB twice

- src/apps/ui/pages/dashboard/Profile.vue
feat: now we can see details of eprs table
> feat: now we can see details of eprs table

- src/apps/api/v1/logs/logs.controller.js
- src/apps/api/v1/logs/logs.router.js
- src/apps/api/v1/logs/logs.validation.js
- src/apps/api/v1/sessions/sessions.queries.js
- src/apps/api/v1/videos/videos.queries.js
- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/pages/dashboard/settings/account/UserDetails.vue
- src/database/migrations/20220718015544_user_details.js
- src/database/migrations/20220731101203_videos.js
- src/utils/multer.js
> feat: now we can upload video per log

- .vscode/settings.json
- src/apps/api/v1/sessions/sessions.controller.js
- src/apps/api/v1/sessions/sessions.queries.js
- src/apps/api/v1/sessions/sessions.router.js
- src/apps/api/v1/sessions/sessions.validation.js
- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/components/dashboard/VideoDetails.vue
- src/apps/ui/pages/dashboard/Videos.vue
> feat: sessions will reflect video details layout

- src/apps/ui/components/dashboard/SessionDetails.vue
- src/bin/server.js
> feat: added an option collapsed/expend all logs at once

- src/apps/ui/components/dashboard/DashboardFooter.vue
- src/apps/ui/components/dashboard/headers/SessionDetailsHeader.vue
- src/apps/ui/components/dashboard/headers/SessionsHeader.vue
- src/apps/ui/components/dashboard/headers/VideosAndProfileHeader.vue
- src/apps/ui/font-awesome.vue.js
- src/apps/ui/pages/dashboard/DashboardHome.vue
- src/apps/ui/pages/dashboard/Profile.vue
- src/apps/ui/pages/dashboard/Videos.vue
- src/apps/ui/router.vue.js
- src/apps/ui/store/app.store.js
see video below
https://user-images.githubusercontent.com/58354193/182740546-3a07a301-d34d-446e-bbe9-e5a353e288ae.mp4
> feat: you can now change videos layout dynamically

- src/apps/ui/components/dashboard/SessionDetails.vue
> feat: added a video preview when adding for a new video

- .vscode/settings.json
- src/apps/api/v1/exercises/exercises.controller.js
- src/apps/api/v1/exercises/exercises.queries.js
- src/apps/api/v1/exercises/exercises.validation.js
- src/apps/api/v1/logs/logs.controller.js
- src/apps/api/v1/logs/logs.queries.js
- src/apps/api/v1/logs/logs.router.js
- src/apps/api/v1/logs/logs.validation.js
- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/main.vue.js
> feat: you can now added multiple exercises at once

- src/apps/ui/components/dashboard/SessionDetails.vue
> feat: added a option to duplicate previous set easily

- package-lock.json
- package.json
- src/apps/api/api.js
- src/apps/api/api.middlewares.js
- src/apps/api/auth/auth.controller.js
- src/apps/api/v1/exercises/exercises.controller.js
- src/apps/api/v1/logs/logs.controller.js
- src/apps/api/v1/logs/logs.queries.js
- src/apps/api/v1/logs/logs.router.js
- src/apps/api/v1/logs/logs.validation.js
- src/apps/api/v1/sessions/sessions.queries.js
- src/apps/ui/components/dashboard/SessionDetails.vue
> feat: added the ability to delete individual log inside a session

- src/apps/api/auth/auth.validation.js
- src/apps/api/v1/users/users.controller.js
- src/apps/api/v1/users/users.queries.js
- src/apps/ui/pages/dashboard/settings/Settings.vue
- src/apps/ui/pages/dashboard/settings/account/DeleteAccount.vue
- src/apps/ui/router.vue.js
> feat: added the ability to delete user account via api/ui

- src/apps/ui/pages/dashboard/sessions/Sessions.vue
> fix: fixed an issue causing total time to not sum

- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/components/dashboard/headers/SessionDetailsHeader.vue
> feat: now you can update session name even after youve completed

- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/components/dashboard/headers/SessionDetailsHeader.vue
- src/apps/ui/pages/dashboard/Community.vue
- src/apps/ui/pages/dashboard/DashboardNotFound.vue
- src/apps/ui/pages/dashboard/DashboardUnauthorized.vue
- src/apps/ui/router.vue.js
> feat: added ui to restrict user for unauthorized access

- src/apps/api/v1/comments/comment.validation.js
- src/apps/api/v1/comments/comments.controller.js
- src/apps/api/v1/comments/comments.queries.js
- src/apps/api/v1/comments/comments.routes.js
- src/apps/api/v1/sessions/sessions.queries.js
- src/apps/api/v1/sessions/sessions.validation.js
- src/apps/api/v1/v1.routes.js
- src/apps/ui/components/dashboard/VideoDetails.vue
- src/apps/ui/pages/dashboard/Community.vue
- src/apps/ui/pages/dashboard/DashboardUnauthorized.vue
- src/database/migrations/20220816204815_comments.js
> feat: added the ability to comment under a session

- .vscode/settings.json
- src/apps/api/v1/sessions/sessions.queries.js
- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/components/dashboard/VideoDetails.vue
- src/apps/ui/pages/regular/Features.vue
- src/config/knexfile.js
- fixed knex connection error bug
- fixed video details were not rendering post author username and profile image
- only render once on the features page
> feat: mass changes

- package-lock.json
- package.json
- src/apps/api/v1/exercises/exercises.queries.js
- src/apps/ui/pages/dashboard/Exercise.vue
- src/bin/server.js
https://user-images.githubusercontent.com/58354193/185723133-75b1495f-7642-4bc2-b514-6eecca43c742.mp4
> feat(exercise-history): added interactive chart to display e1rm

- package-lock.json
- package.json
- src/apps/api/v1/exercises/exercises.controller.js
- src/apps/api/v1/sessions/sessions.controller.js
- src/apps/api/v1/variables/variables.controller.js
- src/apps/api/v1/variables/variables.queries.js
- src/apps/api/v1/variables/variables.router.js
- src/apps/api/v1/variables/variables.validation.js
- src/apps/ui/pages/dashboard/Exercise.vue
- src/apps/ui/pages/dashboard/Profile.vue
> feat: added recovery chart/api

- src/apps/api/v1/videos/videos.controller.js
- src/apps/api/v1/videos/videos.router.js
- src/apps/api/v1/videos/videos.validation.js
- src/apps/ui/components/dashboard/SessionDetails.vue
> feat: added video download option

- package-lock.json
- package.json
- src/apps/ui/components/dashboard/SessionDetails.vue
- src/apps/ui/pages/dashboard/Exercise.vue
- src/apps/ui/pages/dashboard/Profile.vue
> feat: added more data in exercise history and avg sleep function

- src/apps/ui/pages/dashboard/Block.vue
- src/apps/ui/pages/dashboard/tools/calculators/OneRepMaxCalculator.vue.vue
- src/utils/helpers.js
> feat: added one rep max calculator

- src/apps/api/v1/variables/variables.queries.js
- src/apps/cli/commands/users.command.js
- src/apps/ui/pages/dashboard/Profile.vue
- fixed calories not returning by a user
- fixed recovery not returning by a user
- added a new cli commands to add a demo user with out adding mock training data
```bash
$ gains users --add --demo --data # will add mock training data
$ gains users --add --demo# will not add mock training data
```
> fix: bugs causing recovery, calories not to return on single user

- src/apps/cli/commands/view-logs.command.js
- src/apps/ui/App.vue
- src/apps/ui/components/admin/ActivityLog.vue
- src/apps/ui/components/admin/AdminMenuBar.vue
- src/apps/ui/components/regular/RegularHeader.vue
- src/apps/ui/components/shared/Login.vue
- src/apps/ui/layouts/AdminLayout.vue
- src/apps/ui/pages/admin/AdminHome.vue
- src/apps/ui/pages/admin/AdminSessions.vue
- src/apps/ui/pages/admin/AdminUsers.vue
- src/apps/ui/pages/admin/AdminVideos.vue
- src/apps/ui/pages/dashboard/settings/Settings.vue
- src/apps/ui/pages/regular/RegularNotFound.vue
- src/apps/ui/router.vue.js
- src/apps/ui/store/user.store.js
- vite.config.js
> feat: scaffold admin panel with admin stuff (wip)

- .vscode/settings.json
- package-lock.json
- package.json
- src/apps/api/admin/admin.controller.js
- src/apps/api/admin/admin.router.js
- src/apps/api/auth/auth.controller.js
- src/apps/app.js
- src/apps/ui/components/admin/OnlineUsers.vue
- src/apps/ui/components/dashboard/LogoutButton.vue
- src/apps/ui/layouts/AdminLayout.vue
- src/apps/ui/pages/admin/AdminHome.vue
> feat: scaffold socket io for online users

- .env.example
- src/config/env.js
- src/utils/chad.js
> feat: notify

- .env.example
- package-lock.json
- package.json
- src/app/app.js
- src/config/env.js
- src/utils/chad.js
> chore(deps): remove sentry
